Repository chetanbhasney02/Hacktoberfest-2023, pull requests merged in 2023-10, with the labels that each got.

#34 added random quote generator python file
  hacktober_quotes_generator.py
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#31 Random Quote Generator #15 Add files via upload
  palindromeChecker.py
  quoteGenerator/index.html
  quoteGenerator/quote.png
  quoteGenerator/script.js
  quoteGenerator/style.css
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#36 Create palindromechecker.py
  palindromechecker.py
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#44 Create generatepassword.py
  python/generatepassword.py
Labels: good first issue, hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#45 Create URLShortener.py
  URLShortener.py
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#56 Create Linkedlist.cpp
  Linkedlist.cpp
Labels: hacktoberfest-accepted

#57 Create Currency_Exchange_Rate_Calculator.py
  Currency_Exchange_Rate_Calculator.py
Labels: hacktoberfest-accepted

#58 Create Python_BMI_Calculator.py
  Python_BMI_Calculator.py
Labels: hacktoberfest-accepted

#64 ADD Siddartha Datta to Readme list
  README.md
Labels: hacktoberfest-accepted

#67 Create FibonacciSeries.java
  FibonacciSeries.java
Labels: hacktoberfest-accepted

#72 Movie App
  movieland/.eslintrc.cjs
  movieland/.gitignore
  movieland/README.md
  movieland/index.html
  movieland/package-lock.json
  movieland/package.json
  movieland/public/vite.svg
  movieland/src/App.css
  movieland/src/App.jsx
  movieland/src/MovieCard.jsx
  movieland/src/assets/react.svg
  movieland/src/assets/search.svg
  movieland/src/index.css
  movieland/src/main.jsx
  movieland/vite.config.js
Labels: hacktoberfest-accepted
